#spring.application.name=jobportal-backend
server.servlet.context-path=/api
spring.mvc.servlet.path=/v1
spring.application.name=jobportal
spring.profiles.active=dev

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true
